"""add image_url

Revision ID: 1dd279d63eb6
Revises: 47972821bf57
Create Date: 2015-12-20 21:47:12.421761

"""

# revision identifiers, used by Alembic.
revision = '1dd279d63eb6'
down_revision = '47972821bf57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    ### end Alembic commands ###
