"""empty message

Revision ID: 2323a574b092
Revises: 2668c6f19b68
Create Date: 2015-12-01 12:56:22.218745

"""

# revision identifiers, used by Alembic.
revision = '2323a574b092'
down_revision = '2668c6f19b68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
