"""modify table User comments:author

Revision ID: 47972821bf57
Revises: 1962312f3167
Create Date: 2015-12-06 19:30:07.858960

"""

# revision identifiers, used by Alembic.
revision = '47972821bf57'
down_revision = '1962312f3167'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
