"""add column:avatar_hash

Revision ID: 48d260db4cc0
Revises: 2521b5f866d9
Create Date: 2015-12-05 12:33:31.693814

"""

# revision identifiers, used by Alembic.
revision = '48d260db4cc0'
down_revision = '2521b5f866d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
